import{a as R,S as $,i as s}from"./assets/vendor-B5nsgUv9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const p=15,E=R.create({baseURL:"https://pixabay.com/api/",params:{key:"54679610-8cb3c8a86ad83c3b54957649e",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:p}});async function g(t,o=1){return(await E.get("",{params:{q:t,page:o}})).data}const y=document.querySelector(".gallery"),h=document.querySelector(".loader"),b=document.querySelector(".load-more"),B=new $(".gallery a",{captionsData:"alt",captionDelay:250});function L(t){const o=t.map(({webformatURL:n,largeImageURL:l,tags:e,likes:r,views:a,comments:M,downloads:P})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${l}">
          <img class="gallery-image" src="${n}" alt="${e}" loading="lazy" />
        </a>

        <div class="info">
          <p class="info-item"><b>Likes</b> ${r}</p>
          <p class="info-item"><b>Views</b> ${a}</p>
          <p class="info-item"><b>Comments</b> ${M}</p>
          <p class="info-item"><b>Downloads</b> ${P}</p>
        </div>
      </li>`).join("");y.insertAdjacentHTML("beforeend",o),B.refresh()}function x(){y.innerHTML=""}function w(){h.classList.remove("is-hidden")}function S(){h.classList.add("is-hidden")}function O(){b.classList.remove("is-hidden")}function u(){b.classList.add("is-hidden")}const q=document.querySelector(".form"),f=document.querySelector(".load-more");let c="",i=1,d=0,m=!1;u();q.addEventListener("submit",H);f.addEventListener("click",A);async function H(t){if(t.preventDefault(),c=t.target.elements["search-text"].value.trim(),!c){s.warning({message:"Please enter a search query!",position:"topRight"});return}i=1,d=0,m=!1,x(),u(),w();try{const o=await g(c,i);if(d=o.totalHits,!o.hits.length){s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(o.hits),s.success({message:`Hooray! We found ${d} images.`,position:"topRight"}),v()}catch{s.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{S(),q.reset()}}async function A(){u(),f.disabled=!0,i+=1,w();try{const t=await g(c,i);L(t.hits),D(),v()}catch{s.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{S(),f.disabled=!1}}function v(){if(i*p>=d){u(),m||(s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),m=!0);return}O()}function D(){const t=document.querySelector(".gallery-item");if(!t)return;const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
