import{a as M,S as R,i as s}from"./assets/vendor-B5nsgUv9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const m=15,$=M.create({baseURL:"https://pixabay.com/api/",params:{key:"54679610-8cb3c8a86ad83c3b54957649e",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:m}});async function p(o,t=1){return(await $.get("",{params:{q:o,page:t}})).data}const g=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more"),E=new R(".gallery a",{captionsData:"alt",captionDelay:250});function b(o){const t=o.map(({webformatURL:n,largeImageURL:c,tags:e,likes:r,views:i,comments:v,downloads:P})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${c}">
          <img class="gallery-image" src="${n}" alt="${e}" loading="lazy" />
        </a>

        <div class="info">
          <p class="info-item"><b>Likes</b> ${r}</p>
          <p class="info-item"><b>Views</b> ${i}</p>
          <p class="info-item"><b>Comments</b> ${v}</p>
          <p class="info-item"><b>Downloads</b> ${P}</p>
        </div>
      </li>`).join("");g.insertAdjacentHTML("beforeend",t),E.refresh()}function B(){g.innerHTML=""}function L(){y.classList.remove("is-hidden")}function w(){y.classList.add("is-hidden")}function x(){h.classList.remove("is-hidden")}function f(){h.classList.add("is-hidden")}const S=document.querySelector(".form"),u=document.querySelector(".load-more");let l="",a=1,d=0;f();S.addEventListener("submit",O);u.addEventListener("click",H);async function O(o){if(o.preventDefault(),l=o.target.elements["search-text"].value.trim(),!l){s.warning({message:"Please enter a search query!",position:"topRight"});return}a=1,d=0,B(),f(),L();try{const t=await p(l,a);if(d=t.totalHits,!t.hits.length){s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(t.hits),s.success({message:`Hooray! We found ${d} images.`,position:"topRight"}),q()}catch{s.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{w(),S.reset()}}async function H(){u.disabled=!0,a+=1,L();try{const o=await p(l,a);b(o.hits),A(),q()}catch{s.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{w(),u.disabled=!1}}function q(){if(a*m>=d){const t=!u.classList.contains("is-hidden");f(),t&&s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}x()}function A(){const o=document.querySelector(".gallery-item");if(!o)return;const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
